# Development-only PostgreSQL container
# Usage: make db-up (starts), make db-down (stops)
# Or: make dev-full (starts DB + app together)
#
# This is a lightweight alternative to compose.yaml for local development.
# No Caddy proxy, no API container - just the database.
#
# Port: 5433 (to avoid conflict with production PostgreSQL on 5432)
# Connection: postgresql://newsbrief:newsbrief_dev@localhost:5433/newsbrief

services:
  db:
    image: postgres:16
    container_name: newsbrief-db-dev
    environment:
      POSTGRES_DB: newsbrief
      POSTGRES_USER: newsbrief
      POSTGRES_PASSWORD: newsbrief_dev
    volumes:
      - newsbrief_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Host:Container - dev uses 5433 to avoid prod conflict
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newsbrief -d newsbrief"]
      interval: 2s
      timeout: 2s
      retries: 10

volumes:
  newsbrief_dev_data:
