"""Add story_context table for post-synthesis context generation

Revision ID: 035_story_context
Revises: 034_extracted_data
Create Date: 2026-09-21

Foundation for the "Why This Matters" Context Engine (v0.10.0, #285/#214,
ADR-0023 Phase 3). Adds a per-story ``story_context`` table holding
context outputs -- significance angles (#214), and later background/
glossary/precedent (#215) -- generated by a dedicated post-synthesis LLM
call (``app/context_generation.py``), deliberately decoupled from the core
synthesis pass per #285's acceptance criteria ("core story and context
payloads are separable").

This is intentionally *additive* alongside the pre-existing
``stories.why_it_matters`` column (a single free-text paragraph generated
inline in the core synthesis prompt since early versions) rather than a
replacement -- see the ADR-0023 implementation-status note for v0.10.0 for
the rationale (avoiding a breaking change to synthesis prompts, quality
scoring, and the many existing tests that assert on why_it_matters).

``story_id`` (not article_id): unlike extracted_data (migration 034, which
is article-scoped and joins through story_articles for story-level
aggregation), context is inherently story-level -- there is one canonical
synthesis per story, and context is generated *about* that synthesis, not
about any one supporting article.

``content`` is JSONB (not Text) for the same reason as extracted_data's
data_value: shape varies by ``context_type`` --
{"dimension": "economic", "text": "..."} for significance,
{"text": "..."} for background, {"term": "...", "definition": "..."} for
glossary, {"text": "...", "related_story_id": 123} for precedent -- and
JSONB allows querying by sub-key later without a second migration.

``source_story_ids`` is a separate JSONB array (not folded into
``content``) so provenance is uniformly queryable/filterable across all
context_types, satisfying #285's "provenance exists for context statements
where possible" acceptance criterion without forcing every context_type's
content shape to carry it.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "035_story_context"
down_revision: Union[str, Sequence[str], None] = "034_extracted_data"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "story_context",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "story_id",
            sa.Integer(),
            sa.ForeignKey("stories.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("context_type", sa.String(length=20), nullable=False),
        sa.Column("content", postgresql.JSONB(), nullable=False),
        sa.Column("source_story_ids", postgresql.JSONB(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column(
            "generation_method",
            sa.String(length=20),
            nullable=False,
            server_default="llm",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index("idx_story_context_story", "story_context", ["story_id"])
    op.create_index("idx_story_context_type", "story_context", ["context_type"])


def downgrade() -> None:
    op.drop_index("idx_story_context_type", table_name="story_context")
    op.drop_index("idx_story_context_story", table_name="story_context")
    op.drop_table("story_context")
